server:
  port: 7778
  servlet:
    context-path: /api

spring:
  redis:
    expire: 60000
    database: 0 # Redis使用的库
    host: 101.42.231.189
    port: 6379 #端口号
    password: jsb191822redis   #redis密码
    #    lettuce:
    #      pool:
    #        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
    #        max-wait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-idle: 8       # 连接池中的最大空闲连接
    #        min-idle: 1       # 连接池中的最小空闲连接
    timeout: 10000        #  连接超时时间（毫秒）
    cache:
      type: redis
  datasource:
    url: jdbc:mysql://101.42.231.189:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jsb191822
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
          #表明前缀
      table-prefix: "sg_"
        # id生成策略 auto为数据库自增
      id-type: auto
oss:
  accessKey: 0EZHiKJUDkwt8pr5HkwxSiCMYuze6WNzntjrITnF
  secretKey: 2zsN5KyFPxDxi0JAinhI3J8SLtWSqT3bholTntTV
  bucket: bb-blog
  baseUrl: http://img.jx-rg.cn/

ArticleViewCount: Article:viewCount


